server:
  port: 8080

spring:
  data:
    mongodb:
      uri: ${MONGODB_URI}

  mail:
    host: ${MAIL_HOST}
    port: ${MAIL_PORT}
    username: ${MAIL_USERNAME}
    password: ${MAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true

app:
  mail:
    from: ${MAIL_FROM}

security:
  # Không cần đăng nhập (được xử lý TRƯỚC protected-urls)
  publicUrls:
    - "/api/auth/**"          # sign-in, verify OTP, resend OTP...
    - "/api/users/register"   # đổi lại cho đúng path đăng ký của bạn

  # Chỉ giữ những API thật sự cần bảo vệ
  protectedUrls:
    - { urlPattern: "/api/users/**", unauthorizedWwwAuthenticateHeaders: [ "Bearer" ] }

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html