<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>
    
    <parent>
        <groupId>x10.zenfit</groupId>
        <artifactId>ai-service</artifactId>
        <version>0.0.1-SNAPSHOT</version>
    </parent>

    <artifactId>api-portal-service</artifactId>
    <packaging>jar</packaging>
    
    <name>API Portal Service</name>
    <description>Entry point application layer for the Portal Service (Clean Architecture)</description>

    <dependencies>
        <!-- ============================================== -->
        <!-- Internal Modules (Clean Architecture Layers)   -->
        <!-- ============================================== -->



        <!-- ============================================== -->
        <!-- Spring Boot Starters                           -->
        <!-- ============================================== -->
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-web</artifactId>
        </dependency>

        
        <!-- Actuator for monitoring (Health Check, Metrics, v.v) -->
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-actuator</artifactId>
        </dependency>

        <!-- ============================================== -->
        <!-- Test Dependencies                              -->
        <!-- ============================================== -->
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-test</artifactId>
            <scope>test</scope>
        </dependency>
    </dependencies>

    <build>
        <plugins>
            <!-- Đóng gói thành executable jar -->
            <plugin>
                <groupId>org.springframework.boot</groupId>
                <artifactId>spring-boot-maven-plugin</artifactId>
                <configuration>
                    <excludes>
                        <exclude>
                            <groupId>org.projectlombok</groupId>
                            <artifactId>lombok</artifactId>
                        </exclude>
                    </excludes>
                </configuration>
            </plugin>
        </plugins>
    </build>
</project>